checks:
  php: true

filter:
  paths:
    - src/*

build:
  image: default-bionic

  environment:
    php:
      version: 8.1.18
      ini:
        xdebug.mode: coverage

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    phpunit:
      services:
        db-mssql:
          image: mcr.microsoft.com/mssql/server:2017-latest

          # Define any additional environment variables that are needed by the service.
          env:
            SA_PASSWORD: YourStrong!Passw0rd
            ACCEPT_EULA: Y
            MSSQL_PID: Developer

          # We automatically forward these ports from your localhost to the service's port.
          # Alternatively, you can also access the service on the "$SERVICE_SOME_NAME_IP"
          # environment variable.
          ports:
            # Forward 127.0.0.1:12345 -> SERVICE_IP:12345
            - 1433

          # If your service writes data to disk like most databases do, you can significantly
          # speed up tests by mounting a ramdisk at those paths.
          ramdisks:
            - /var/lib/data

        db-mysql:
          image: mysql:8.0.29

          # Define any additional environment variables that are needed by the service.
          env:
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_ROOT_PASSWORD: ''
            MYSQL_DATABASE: yiitest

          # We automatically forward these ports from your localhost to the service's port.
          # Alternatively, you can also access the service on the "$SERVICE_SOME_NAME_IP"
          # environment variable.
          ports:
            # Forward 127.0.0.1:12345 -> SERVICE_IP:12345
            - 3306

          # If your service writes data to disk like most databases do, you can significantly
          # speed up tests by mounting a ramdisk at those paths.
          ramdisks:
            - /var/lib/data

        db-pgsql:
          image: postgres:14

          # Define any additional environment variables that are needed by the service.
          env:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: yiitest

          # We automatically forward these ports from your localhost to the service's port.
          # Alternatively, you can also access the service on the "$SERVICE_SOME_NAME_IP"
          # environment variable.
          ports:
            # Forward 127.0.0.1:12345 -> SERVICE_IP:12345
            - 5432

          # If your service writes data to disk like most databases do, you can significantly
          # speed up tests by mounting a ramdisk at those paths.
          ramdisks:
            - /var/lib/data

        db-oracle:
          image: gvenzl/oracle-xe:21

          # We automatically forward these ports from your localhost to the service's port.
          # Alternatively, you can also access the service on the "$SERVICE_SOME_NAME_IP"
          # environment variable.
          ports:
            # Forward 127.0.0.1:12345 -> SERVICE_IP:12345
            - 1521

          env:
            ORACLE_DATABASE : yiitest
            ORACLE_PASSWORD : root

          # If your service writes data to disk like most databases do, you can significantly
          # speed up tests by mounting a ramdisk at those paths.
          ramdisks:
            - /var/lib/data

      tests:
        before:
          - curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          - curl https://packages.microsoft.com/config/ubuntu/18.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
          - sudo apt-get update -y
          - sudo ACCEPT_EULA=Y apt-get install mssql-tools unixodbc-dev -y
          - sudo ls /opt/mssql-tools/bin/sqlcmd*
          - /opt/mssql-tools/bin/sqlcmd -S 127.0.0.1 -U SA -P 'YourStrong!Passw0rd' -Q 'CREATE DATABASE yiitest'
          - pecl -q install pdo_sqlsrv
          - sudo mkdir -p /opt/oracle
          - sudo curl -k -L --output /opt/oracle/instantclient-basic-linux.x64-21.3.0.0.0.zip https://download.oracle.com/otn_software/linux/instantclient/213000/instantclient-basic-linux.x64-21.3.0.0.0.zip
          - sudo curl -k -L --output /opt/oracle/instantclient-sdk-linux.x64-21.3.0.0.0.zip https://download.oracle.com/otn_software/linux/instantclient/213000/instantclient-sdk-linux.x64-21.3.0.0.0.zip
          - sudo unzip /opt/oracle/instantclient-basic-linux.x64-21.3.0.0.0.zip -d /opt/oracle
          - sudo unzip /opt/oracle/instantclient-sdk-linux.x64-21.3.0.0.0.zip -d /opt/oracle
          - sudo apt-get install libaio1 -y
          - export ORACLE_HOME=/opt/oracle/instantclient_21_3
          - sudo sh -c "echo /opt/oracle/instantclient_21_3 > /etc/ld.so.conf.d/oracle-instantclient.conf"
          - sudo ldconfig
          - curl -k -L --output /home/scrutinizer/oci8-3.0.1.tgz https://pecl.php.net/get/oci8-3.0.1.tgz
          - cd /home/scrutinizer
          - tar -zxf oci8-3.0.1.tgz
          - cd oci8-3.0.1
          - phpize
          - ./configure --with-oci8=instantclient,/opt/oracle/instantclient_21_3
          - make
          - sudo make install
          - sudo ldconfig
          - curl -k -L --output /home/scrutinizer/php-8.1.18.tar.gz https://www.php.net/distributions/php-8.1.18.tar.gz
          - cd /home/scrutinizer
          - tar -zxf php-8.1.18.tar.gz
          - cd php-8.1.18/ext/pdo_oci
          - phpize
          - ./configure --with-pdo-oci=instantclient,/opt/oracle/instantclient_21_3
          - make
          - sudo make install
          - sudo ldconfig
          - cd /home/scrutinizer/build/
          - composer require yiisoft/db-mssql --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi
          - composer require yiisoft/db-mysql --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi
          - composer require yiisoft/db-oracle --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi
          - composer require yiisoft/db-pgsql --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi
          - composer require yiisoft/db-sqlite --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi
          - echo 'extension=pdo_oci' >> /home/scrutinizer/.phpenv/versions/8.1.18/etc/php.ini

        override:
          - command: ./vendor/bin/phpunit --coverage-clover ./coverage.xml
            coverage:
              file: coverage.xml
              format: php-clover
