name: mutation test

on:
  pull_request:
    paths: &paths
      - 'src/**'
      - 'sql/**'
      - 'tests/**'
      - 'composer.json'
      - 'phpunit.xml.dist'
      - 'infection.json.dist'
      - '.github/workflows/mutation.yml'
  push:
    branches: ['master']
    paths: *paths

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mutation:
    name: PHP ${{ matrix.php }}-${{ matrix.os }}

    env:
      extensions: pdo, pdo_mysql, pdo_pgsql, pdo_oci, pdo_sqlite, pdo_sqlsrv, oci8

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest

        php:
          - 8.3

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest # zizmor: ignore[unpinned-images]
        env:
          MSSQL_SA_PASSWORD: YourStrong!Passw0rd
          ACCEPT_EULA: Y
          MSSQL_PID: Developer
        ports:
          - 1433:1433
        options: --name=mssql --health-cmd="/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U SA -P 'YourStrong!Passw0rd' -Q 'SELECT 1'" --health-interval=10s --health-timeout=5s --health-retries=3
      mysql:
        image: mysql:9 # zizmor: ignore[unpinned-images]
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_PASSWORD: ''
          MYSQL_DATABASE: yiitest
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      oci:
        image: gvenzl/oracle-xe:21 # zizmor: ignore[unpinned-images]
        ports:
          - 1521:1521
        env:
          ORACLE_DATABASE : yiitest
          ORACLE_PASSWORD : root
        options: >-
          --name=oci
          --health-cmd healthcheck.sh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
      postgres:
        image: postgres:15 # zizmor: ignore[unpinned-images]
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: yiitest
        ports:
          - 5432:5432
        options: --name=postgres --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout.
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Create MS SQL Database.
        run: docker exec -i mssql /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U SA -P 'YourStrong!Passw0rd' -Q 'CREATE DATABASE yiitest'

      - name: Install ODBC driver.
        run: |
          sudo curl https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18

      - name: Install PHP with extensions.
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: "${{ matrix.php }}"
          extensions: ${{ env.extensions }}
          ini-values: memory_limit=-1
          coverage: pcov
          tools: composer:v2

      - name: Update composer.
        run: composer self-update

      - name: Install db-pgsql.
        run: composer require yiisoft/db-mssql yiisoft/db-mysql yiisoft/db-oracle yiisoft/db-pgsql yiisoft/db-sqlite --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

      - name: Run infection.
        run: |
          vendor/bin/roave-infection-static-analysis-plugin --threads=2 --ignore-msi-with-no-mutations
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
