on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

  push:
    branches: ['master']
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

name: oracle

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
jobs:
  tests:
    name: PHP ${{ matrix.php }}-oracle-${{ matrix.oracle }}

    env:
      extensions: pdo, pdo_oci, oci8

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 2
      matrix:
        php:
          - 8.5

        oracle:
          - 18
          - 21

        include:
          - php: 8.1
            oracle: 21
          - php: 8.2
            oracle: 21
          - php: 8.3
            oracle: 21
          - php: 8.4
            oracle: 21

    services:
      oci:
        image: gvenzl/oracle-xe:${{ matrix.oracle }} # zizmor: ignore[unpinned-images]
        ports:
          - 1521:1521
        env:
          ORACLE_DATABASE : yiitest
          ORACLE_PASSWORD : root
        options: >-
          --name=oci
          --health-cmd healthcheck.sh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Checkout.
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false

      - name: Install PHP with extensions.
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.extensions }}
          ini-values: date.timezone='UTC'
          coverage: pcov
          tools: composer:v2

      - name: Update composer.
        run: composer self-update

      - uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda
        with:
          composer-options: "--prefer-dist --no-interaction --no-progress --ansi"

      - name: Install db-oracle.
        run: composer require yiisoft/db-oracle --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

      - name: Run tests with phpunit.
        run: vendor/bin/phpunit --testsuite=Oracle --coverage-clover=coverage.xml --colors=always

      - name: Upload coverage to Codecov.
        if: matrix.php == '8.5'
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
