on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

  push:
    branches: ['master']
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

name: pgsql

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
jobs:
  tests:
    name: PHP ${{ matrix.php }}-pgsql-${{ matrix.pgsql }}

    env:
      extensions: pdo, pdo_pgsql

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 3
      matrix:
        php:
          - 8.5

        pgsql:
          - 9
          - 10
          - 11
          - 12
          - 13
          - 14
          - 15
          - 16
          - 17
          - 18
          - latest

        include:
          - php: 8.1
            pgsql: latest
          - php: 8.2
            pgsql: latest
          - php: 8.3
            pgsql: latest
          - php: 8.4
            pgsql: latest

    services:
      postgres:
        image: postgres:${{ matrix.pgsql }} # zizmor: ignore[unpinned-images]
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: yiitest
        ports:
          - 5432:5432
        options: --name=postgres --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout.
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        with:
          persist-credentials: false

      - name: Install PHP with extensions.
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.extensions }}
          ini-values: date.timezone='UTC'
          coverage: pcov
          tools: composer:v2

      - name: Update composer.
        run: composer self-update

      - uses: ramsey/composer-install@a8d0d959dab41457692a5e2041bd9b757a119e3f
        with:
          composer-options: "--prefer-dist --no-interaction --no-progress --ansi"

      - name: Install db-pgsql.
        run: composer require yiisoft/db-pgsql --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

      - name: Run tests with phpunit.
        run: vendor/bin/phpunit --testsuite=Pgsql --coverage-clover=coverage.xml --colors=always

      - name: Upload coverage to Codecov.
        if: matrix.php == '8.5'
        uses: codecov/codecov-action@ab904c41d6ece82784817410c45d8b8c02684457
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
